### ISSUE TITLE
Returns false but page exists and is accessible via web browser

### ISSUE THREAD

**Issue by BartusZak** [Richienb/url-exist#30]
**Describe the bug**
Provided working URL and method returned false. Page is accessible via web browser.

**To Reproduce**
```javascript
const urlExist = require("url-exist");

const url = "https://sklep.loretanki.pl/produkt/opowiesci-aniola/"

await urlExist(url); // returns false
```

**Expected behavior**
Should return `true`

**Comment by Richienb** [comment]
This is because `node-fetch` is having trouble verifying SSL certificates:

```sh
(node:16152) UnhandledPromiseRejectionWarning: FetchError: request to https://sklep.loretanki.pl/produkt/opowiesci-aniola/ failed, 
reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (file:///C:/Users/richi/Documents/GitHub/url-exist/node_modules/node-fetch/src/index.js:94:11)    
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are 
not handled will terminate the Node.js process with a non-zero exit code.
```

Try opening an issue there instead.
